### ISSUE TITLE
error loading file

### ISSUE THREAD

**Issue by joanlandry** [sysrepo/dnsmasq-sysrepo#1]
I am trying to run the instructions in the readme file and ran into the following error. Any idea on how to fix this issue - or what is causeing this problem:
[root@MaestrOS yang]# sysrepocfg --import=dnsmasq.xml --datastore=startup sysrepo-dnsmasq
[ERR](srcfg_ly_log_cb:84) libyang: Unknown element "netconf-state".
[ERR](rp_dt_commit:674) Data validation failed: Unknown element "netconf-state".
[ERR](sr_commit:1111) Error by processing of commit request.
[ERR](srcfg_import_datastore:665) Error returned from sr_commit: Validation of the changes failed.
Errors were encountered during importing. Cancelling the operation.
[root@MaestrOS yang]# 

Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)
## Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features

ietf-netconf                  | 2011-06-01 |                     |             |                               |
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               |
ietf-ip                       | 2014-06-16 |                     |             |                               |
iana-if-type                  | 2014-05-08 |                     |             |                               |
turing-machine                | 2013-12-27 | root:root           | 666         |                               |
sysrepo-dnsmasq               | 2016-01-22 | root:root           | 666         |                               |
ietf-netconf-with-defaults    | 2011-06-01 |                     |             |                               |

**Comment by rastislavs** [comment]
Hi,

it was a bug in sysrepo, fixed in commit https://github.com/sysrepo/sysrepo/pull/259/commits/81e5ffc789132988a11cb26497435bf8bcd46587
